# fly.toml app configuration file for frontend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "cat-chat"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REACT_APP_API_BASE_URL = "https://cat-chat-backend.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"